salesforce/orchard

- README.md
Added a version 1 of the Orchard README. A developer guide that describes the process of developing new activities, more workable examples, and more design background will be added in future versions.
> [docs] README.md v1

- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/resource/AwsTag.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/resource/Ec2Resource.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/resource/EmrResource.scala
- version.sbt
support tags for aws ec2 and emr resources
> Ec2 tagging

- build.sbt
- version.sbt
Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-36944
> update scala version, update deps

- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/resource/EmrResource.scala
- version.sbt
risk: low
Fix for issue https://github.com/salesforce/orchard/issues/48
> Fix by making Instance Profile ssh key optional

- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/resource/Ec2Resource.scala
- version.sbt
> Allow security groups for ec2 instances

- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/activity/ShellCommandActivity.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/activity/ShellScriptActivity.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/resource/EmrResource.scala
- version.sbt
> Fix bug in shell activity s3 path

- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/activity/ShellCommandActivity.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/activity/ShellScriptActivity.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/util/S3Uri.scala
- version.sbt
> Make output uri and timeout optional

- orchard-core/src/main/scala/com/salesforce/mce/orchard/db/OrchardDatabase.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ResourceMgr.scala
- orchard-ws/app/controllers/WorkflowController.scala
- version.sbt
> Validate terminateAfter before insert into DB

- orchard-ws/app/controllers/WorkflowController.scala
- version.sbt
Merge request adds workflow request validation, per PR https://github.com/salesforce/orchard/issues/63.
More specifically, MR adds logic to check whether
- every resources refer by activities are defined
- dependent activities are defined
{risk:low}
> Add workflow request resource and activity validation

- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/resource/EmrResource.scala
- version.sbt
> Support instance groups for EMR resource to set spot instance bid price

- build.sbt
- version.sbt
force bump guava to resolve critical vulnerability.
> fix: vulnerability remediation

- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/activity/EmrActivity.scala
- version.sbt
> EmrActivity stepState CANCELLED map to status.Failed

- orchard-core/src/main/scala/com/salesforce/mce/orchard/io/ResourceIO.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ResourceMgr.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/resource/Ec2Resource.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/resource/EmrResource.scala
- version.sbt
> On demand after max attempt

- orchard-core/src/main/resources/reference.conf
- orchard-core/src/main/scala/com/salesforce/mce/orchard/OrchardSettings.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/OrchardSystem.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ActivityAttempt.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ActivityMgr.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/WorkflowMgr.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/activity/Ec2Activity.scala
- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/activity/EmrActivity.scala
- orchard-ws/app/services/OrchardSystemService.scala
- version.sbt
> Reduce progress check cadence

- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ActivityAttempt.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ActivityMgr.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ResourceInstance.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ResourceMgr.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/WorkflowMgr.scala
- version.sbt
Using Behaviors.receiveSignal to log signal PostStop for actors.  Including ActivityAttempt, ActivityMgr, ResourceInstance, ResourceMgr, WorkflowMgr
> receiveSignal to log actors PostStop

- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/WorkflowMgr.scala
- version.sbt
> Carry on previous failed status

- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ResourceInstance.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ResourceMgr.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/util/RetryHelper.scala
- version.sbt
> Delayed creating resource instances

- orchard-core/src/main/resources/reference.conf
- orchard-core/src/main/scala/com/salesforce/mce/orchard/OrchardSettings.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ActivityMgr.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/ResourceMgr.scala
- orchard-core/src/main/scala/com/salesforce/mce/orchard/system/actor/WorkflowMgr.scala
- version.sbt
> Make resource attempt delay configurable

- build.sbt
- version.sbt
> bump logback-classic 1.4.14

- project/plugins.sbt
- version.sbt
after logback 1.4.14, play version bump to fix 
[error] java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL)'
> bump play to 2.9.1 to match logback-classic 1.4.14

- orchard-provider-aws/src/main/scala/com/salesforce/mce/orchard/io/aws/activity/ShellScriptActivity.scala
- version.sbt
add region and endpoint options to allow them to be overridden
> add region and endpoint options for shell script activity

- README.md
- orchard-ws/app/workflow/Controller.scala
- orchard-ws/app/workflow/Router.scala
- version.sbt
add an endpoint for
GET(p"/$id/status")
Sprinkler to call the above, so to not get into an infinite loop of trying to activate a workflow already activated in Orchard
> add an endpoint to check workflow status

- .circleci/config.yml
- README.md
- example/auth-config.conf
- orchard-ws/app/utils/Authorization.scala
- orchard-ws/app/utils/AuthorizationSettings.scala
- orchard-ws/conf/application.conf
- version.sbt
Authorization check (optional by conf) on x-forwarded-client-cert header
> Enhance header auth on x-forwarded-client-cert
